<?php
//Somunachimso Bernard Nzenwa_AGG801_@00652263
require_once('Template/header.phtml') ?>
<p>Welcome to Lightning Chargers! An electric vehicle charging site.</p>
<p>This system allows you to log in or signup securely through password encryption.</p>
<p>Users can send a request to use a charge point.</p>
<p>It was built with appropriate data, tested accordingly and has a variety of features, including security.</p>
<p>Simply login below to get started!</p>
<br>
<form id="login" method="post" action="index.php" enctype="application/x-www-form-urlencoded">
    <p>Please enter your username and password:</p>
    <p><small class="text-danger"><?php if(isset($view->wrongLogIn)) {echo $view->wrongLogIn;}?></small></p>
    <label for="username">Username<span style="color: red">&#42</span></label>
    <input type="email" id="username" name="username" class="form-control" placeholder="Email" required>

    <label for="password">Password<span style="color: red">&#42</span></label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
    <button type="submit" name="loginBtn" class="loginBtn" value="Login">Login</button>
    <p class="backLink">Don't have an account? <a href="signup.php"><strong>Sign up</strong></a> instead!</p>
</form>
<?php
require_once('Template/footer.phtml') ?>